import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, Users, CheckSquare, BookOpen, RefreshCw, ReceiptIndianRupee, Landmark, FileText, BarChart3, Bell, Settings, Search, Plus, ChevronRight, CircleAlert, Clock3, FileWarning, TrendingUp, ArrowUpRight, Bot, X, Send, Menu, LogOut, ShieldCheck } from 'lucide-react';
import './styles.css';

const nav = [
  ['Dashboard', LayoutDashboard], ['Clients', Users], ['Tasks', CheckSquare], ['Books', BookOpen], ['Recon', RefreshCw], ['GST', ReceiptIndianRupee], ['TDS', Landmark], ['Documents', FileText], ['Insights', BarChart3]
];
const rows = [
  ['ABC Traders Pvt Ltd', 'GSTR-3B', '11 Oct 2026', 'Documents pending', 'amber'],
  ['Metro Enterprises', 'TDS payment', '07 Oct 2026', 'Needs review', 'red'],
  ['Sunrise Foods', 'Bank reconciliation', 'Today', '3 exceptions', 'red'],
  ['Apex Solutions LLP', 'Monthly books', '09 Oct 2026', 'In progress', 'blue'],
];
const taskData = [
  ['Reconcile HDFC bank statement', 'ABC Traders Pvt Ltd', 'Today', 'Needs Review'],
  ['Request purchase invoices', 'Metro Enterprises', 'Today', 'Open'],
  ['Verify GSTR-2B mismatch', 'Sunrise Foods', '07 Oct', 'In Progress'],
  ['Prepare monthly MIS', 'Apex Solutions LLP', '09 Oct', 'Open'],
];
const clientData = [
  ['ABC Traders Pvt Ltd', 'Trading', 'GST + Books', 'Amber'],
  ['Metro Enterprises', 'Manufacturing', 'TDS + GST', 'Red'],
  ['Sunrise Foods', 'FMCG', 'Books + Recon', 'Amber'],
  ['Apex Solutions LLP', 'Services', 'Books + MIS', 'Green'],
  ['Nexa Retail Pvt Ltd', 'Retail', 'GST + Books', 'Green'],
];

function Badge({children, color='blue'}) { return <span className={'badge '+color}>{children}</span> }
function KPI({icon: Icon, number, label, color, onClick}) { return <button className="kpi" onClick={onClick}><span className={'iconbox '+color}><Icon size={20}/></span><span><b>{number}</b><small>{label}</small></span><ChevronRight size={18} className="muted"/></button> }
function PageHeader({title, description, button}) { return <div className="pagehead"><div><h1>{title}</h1><p>{description}</p></div>{button && <button className="primary"><Plus size={17}/>{button}</button>}</div> }

function Dashboard({navigate}) { return <>
  <PageHeader title="Dashboard" description="Welcome back, Rahul. Here is what needs attention today." button="New task"/>
  <div className="filters"><button>All clients ▾</button><button>All entities ▾</button><button>Oct 2026 ▾</button><span className="live"><span/> Live data demo</span></div>
  <div className="kpis">
    <KPI icon={Clock3} number="12" label="Due in 7 days" color="orange" onClick={()=>navigate('Tasks')}/>
    <KPI icon={ShieldCheck} number="18" label="Pending review" color="purple" onClick={()=>navigate('Tasks')}/>
    <KPI icon={CircleAlert} number="27" label="Open exceptions" color="red" onClick={()=>navigate('Recon')}/>
    <KPI icon={FileWarning} number="9" label="Missing documents" color="teal" onClick={()=>navigate('Documents')}/>
  </div>
  <div className="grid two">
    <section className="card"><div className="cardhead"><div><h2>Compliance calendar</h2><p>Upcoming client deadlines</p></div><button className="link">View all</button></div><div className="deadline-list">{rows.map((r,i)=><div className="deadline" key={i}><div className="date"><b>{r[2].split(' ')[0]}</b><span>{r[2].split(' ').slice(1).join(' ') || 'Oct'}</span></div><div className="deadlineinfo"><b>{r[0]}</b><small>{r[1]}</small></div><Badge color={r[4]}>{r[3]}</Badge></div>)}</div></section>
    <section className="card"><div className="cardhead"><div><h2>Action required</h2><p>Highest-priority items</p></div><button className="link" onClick={()=>navigate('Tasks')}>Open tasks</button></div><div className="actions"><div><span className="dot red"/><div><b>8 GSTR-2B mismatches</b><small>Review ITC exceptions for ABC Traders</small></div><button className="arrow" onClick={()=>navigate('GST')}><ArrowUpRight size={17}/></button></div><div><span className="dot orange"/><div><b>5 unmatched bank entries</b><small>Sunrise Foods · September 2026</small></div><button className="arrow" onClick={()=>navigate('Recon')}><ArrowUpRight size={17}/></button></div><div><span className="dot purple"/><div><b>3 client approvals pending</b><small>Document confirmation required</small></div><button className="arrow" onClick={()=>navigate('Documents')}><ArrowUpRight size={17}/></button></div><div><span className="dot teal"/><div><b>9 documents not received</b><small>Send requests before due date</small></div><button className="arrow" onClick={()=>navigate('Documents')}><ArrowUpRight size={17}/></button></div></div></section>
  </div>
  <div className="grid two lower">
    <section className="card"><div className="cardhead"><div><h2>Reconciliation status</h2><p>October 2026 across all entities</p></div><button className="link" onClick={()=>navigate('Recon')}>View queue</button></div><div className="recon"><div className="donut"><div><b>82%</b><small>matched</small></div></div><div className="legend"><p><span className="dot green"/> Matched <b>1,248</b></p><p><span className="dot orange"/> Needs review <b>114</b></p><p><span className="dot red"/> Exceptions <b>27</b></p></div></div></section>
    <section className="card"><div className="cardhead"><div><h2>Cash & collections</h2><p>Portfolio overview</p></div><button className="link" onClick={()=>navigate('Insights')}>View insights</button></div><div className="money"><div><small>Receivables due</small><b>₹8.40L</b><span className="negative">↑ 12.4% vs last month</span></div><div><small>Cash at bank</small><b>₹22.65L</b><span className="positive">● Healthy across 4 entities</span></div></div><div className="bars">{[42,56,38,71,60,86,64,79,93,72,88,96].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></section>
  </div>
</> }

function Clients(){ return <><PageHeader title="Clients" description="Manage entities, assignments, compliance scope, and health." button="Add client"/><section className="card tablecard"><div className="toolbar"><div className="input"><Search size={17}/><input placeholder="Search clients"/></div><button>All statuses ▾</button></div><table><thead><tr><th>Client</th><th>Industry</th><th>Services</th><th>Health</th><th></th></tr></thead><tbody>{clientData.map((c,i)=><tr key={i}><td><b>{c[0]}</b><small>FY 2026–27</small></td><td>{c[1]}</td><td>{c[2]}</td><td><Badge color={c[3].toLowerCase()}>{c[3]}</Badge></td><td><button className="arrow"><ChevronRight size={18}/></button></td></tr>)}</tbody></table></section></> }
function Tasks(){ return <><PageHeader title="Tasks" description="Track accounting, compliance, and review work across clients." button="Create task"/><section className="card tablecard"><div className="toolbar"><div className="input"><Search size={17}/><input placeholder="Search tasks"/></div><button>My tasks ▾</button><button>Status ▾</button></div><table><thead><tr><th>Task</th><th>Client</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>{taskData.map((t,i)=><tr key={i}><td><b>{t[0]}</b><small>Assigned to Rahul Mehta</small></td><td>{t[1]}</td><td>{t[2]}</td><td><Badge color={t[3]==='Needs Review'?'purple':t[3]==='In Progress'?'blue':'amber'}>{t[3]}</Badge></td><td><button className="arrow"><ChevronRight size={18}/></button></td></tr>)}</tbody></table></section></> }
function SimplePage({title, description, type}) { const content = { Books:['Books overview','Draft journals, invoices, expense records, and ledgers are ready for review.'], Recon:['Reconciliation queue','Review bank and ledger matches with evidence before approval.'], GST:['GST workspace','Prepare workpapers, track GSTR-2B exceptions, and manage return status.'], TDS:['TDS workspace','Track deductions, challans, returns, and filing deadlines.'], Documents:['Documents','Collect, process, and review client financial documents.'], Insights:['Financial insights','View cash flow, receivables, profitability, and key business trends.']}[type] || [title,description]; return <><PageHeader title={content[0]} description={content[1]} button={type==='Documents'?'Upload document':undefined}/><div className="feature-grid"><section className="card feature"><span className="bigicon"><Bot size={26}/></span><h2>Kanishka AI assistant</h2><p>Ask questions about this workspace, summarize exceptions, or draft a review checklist.</p><button className="primary">Ask Kanishka</button></section><section className="card feature"><span className="bigicon greenbg"><TrendingUp size={26}/></span><h2>Demo data ready</h2><p>This screen is structured for live financial data, secure workflows, and approval controls in the production version.</p><button className="secondary">View sample records</button></section></div><section className="card empty"><FileText size={31}/><h3>{type} records will appear here</h3><p>Use the navigation and sample dashboard links to explore the Kanishka AI demo.</p></section></> }
function Chat({close}) { const [messages,setMessages]=useState([{from:'ai',text:'Hello! I’m Kanishka AI. I can help explain dashboard alerts, prepare a client reminder, or summarize reconciliation exceptions.'}]); const [input,setInput]=useState(''); const send=()=>{if(!input.trim()) return; const user=input; setMessages(m=>[...m,{from:'user',text:user},{from:'ai',text:'Demo response: I would analyze your permitted client data, show source-linked evidence, and prepare a review-ready answer. In the live version, no record is changed without your approval.'}]);setInput('')};return <aside className="chat"><div className="chathead"><div><span className="botmini"><Bot size={17}/></span><b>Ask Kanishka</b><small>AI finance workdesk</small></div><button onClick={close}><X size={19}/></button></div><div className="messages">{messages.map((m,i)=><div className={'message '+m.from} key={i}>{m.text}</div>)}</div><div className="suggestions"><button onClick={()=>setInput('Summarize my open exceptions')}>Summarize exceptions</button><button onClick={()=>setInput('Draft a document reminder')}>Draft reminder</button></div><div className="composer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask about your finance work..."/><button onClick={send}><Send size={17}/></button></div></aside>}
function App(){const [active,setActive]=useState('Dashboard'); const [chat,setChat]=useState(false); const [mobile,setMobile]=useState(false); const page=useMemo(()=> active==='Dashboard'?<Dashboard navigate={setActive}/>:active==='Clients'?<Clients/>:active==='Tasks'?<Tasks/>:<SimplePage type={active}/>,[active]);return <div className="app"><aside className={'sidebar '+(mobile?'open':'')}><div className="brand"><div className="logo">K</div><div><b>Kanishka AI</b><small>Accounting & Compliance</small></div></div><nav>{nav.map(([name,Icon])=><button key={name} className={active===name?'active':''} onClick={()=>{setActive(name);setMobile(false)}}><Icon size={19}/><span>{name}</span></button>)}</nav><div className="sidebottom"><button onClick={()=>setActive('Settings')}><Settings size={19}/><span>Settings</span></button><button><LogOut size={19}/><span>Sign out</span></button></div></aside><main><header><button className="mobilemenu" onClick={()=>setMobile(!mobile)}><Menu size={21}/></button><div className="search"><Search size={18}/><input placeholder="Search clients, tasks, documents..."/><kbd>⌘ K</kbd></div><div className="headeractions"><button className="ask" onClick={()=>setChat(true)}><Bot size={18}/>Ask Kanishka</button><button className="bell"><Bell size={19}/><i/></button><button className="avatar">RM</button></div></header><div className="content">{page}</div></main>{chat&&<Chat close={()=>setChat(false)}/>}<div className="toast">Demo mode · No live financial data is stored</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
